version: "3.9"
services:
  dev:
    image: sehandev/softsplat
    volumes:
      - .:/workspace
      - ./ray_results:/home/user/ray_results
    environment:
      - TZ=Asis/Seoul
      - DEBIAN_FRONTEND=noninteractive
    shm_size: "64gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1", "2", "3"]
              capabilities: [gpu]
    stdin_open: true
